# Theme
remote_theme: mmistakes/minimal-mistakes

# Site settings
locale: "de-DE"
title: "babymarkt.de tech jobs"
title_separator: "-"
logo: "/assets/images/header_logo.png"
name: "babymarkt.de GmbH"
url: https://baby-markt.github.io
baseurl: "/jobs"
repository: "Baby-Markt/jobs"
offers_email: "bewerbung.shop@babymarkt.de"

search: true
search_full_content: true

# Site author
author:
  name: "Niklas Funke"
  location: "Dortmund, NRW"
  email: "funke@babymarkt.de"
  avatar: "https://www.xing.com/img/users/3/3/9/889c08534.7114152,11.256x256.jpg"
  uri: "https://www.babymarkt.de"
  xing: "Niklas_Funke2"
  github: "baby-markt"

# Reading files
include:
- _pages
- _backend
- _frontend
- _infrastructure

# Exclude files and directories
exclude:
- dev

# Collections
collections:
  backend:
    output: true
    permalink: /:collection/:path/
  frontend:
    output: true
    permalink: /:collection/:path/
  infrastructure:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
# _pages
- scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: false
# _backend
- scope:
    path: ""
    type: backend
  values:
    layout: single
    author_profile: true
    header:
      show_overlay_excerpt: false
      overlay_color: "#000"
      overlay_filter: "0.5"
      cta_label: "Jetzt bewerben"
      cta_url: "mailto:bewerbung.shop@babymarkt.de"
# _frontend
- scope:
    path: ""
    type: frontend
  values:
    layout: single
    author_profile: true
    header:
      show_overlay_excerpt: false
      overlay_color: "#000"
      overlay_filter: "0.5"
      cta_label: "Jetzt bewerben"
      cta_url: "mailto:bewerbung.shop@babymarkt.de"
# _infrastructure
- scope:
    path: ""
    type: infrastructure
  values:
    layout: single
    author_profile: true
    header:
      show_overlay_excerpt: false
      overlay_color: "#000"
      overlay_filter: "0.5"
      cta_label: "Jetzt bewerben"
      cta_url: "mailto:bewerbung.shop@babymarkt.de"