# Theme
remote_theme: mmistakes/minimal-mistakes

# Site settings
locale: "de-DE"
title: "babymarkt.de tech jobs"
title_separator: "-"
name: &name "Niklas Funke"
url: https://baby-markt.github.io
baseurl: "/jobs"
repository: "Baby-Markt/jobs"

search: true
search_full_content: true

# Site author
author:
  name: *name
  location: "Dortmund, NRW"
  email:
  uri: "https://www.babymarkt.de"
  xing: "u-nik"

# Reading files
include:
- _backend
- _frontend
- _infrastructure

# Collections
collections:
  backend:
    output: true
    permalink: /:collection/:name
  frontend:
    output: true
    permalink: /:collection/:name
  infrastructure:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
# _backend
- scope:
    path: "/backend/"
    type: backend
  values:
    layout: single
    author_profile: true
# _frontend
- scope:
    path: "/frontend/"
    type: frontend
  values:
    layout: single
    author_profile: true
# _infrastructure
- scope:
    path: "/infrastructure/"
    type: infrastructure
  values:
    layout: single
    author_profile: true